### ISSUE TITLE
No documentation for 'locale' feature

### ISSUE THREAD

**Issue by MauriceHandwerker** [esx-framework/esx-documentation#108]
The locale feature (TranslateCap / _U) is used in almost every resource.
But you cant find any documentation on how to use it. The only way to see what the feature can do is to talk/chat with other developers or search through the source code. I think there should be a better documentation for these kind of features.

**Comment by Gellipapa** [comment]
@MauriceHandwerker Hi! We're in the process of rewriting esx docs so we're going to start writing this one too. Thank you very much.
