### ISSUE TITLE
Add warning that xPlayer must be checked for nil value before indexing

### ISSUE THREAD

**Issue by pablordgez** [esx-framework/esx-documentation#109]
I've had to fix so many scripts that fail because they try to iterate xPlayers and try to get some information about a player without checking whether it's nil. A warning somewhere in the documentation would be nice

**Comment by Arctos2win** [comment]
> so many scripts that fail because they try to iterate xPlayers and try to get some information a

What function are you talking about ?

**Comment by pablordgez** [comment]
Any function that iterates through xPlayers without checking whether xPlayer is nil is prone to fail, and I've seen this countless times, there should be a warning somewhere in the documentation that this must be checked

**Comment by Gellipapa** [comment]
Will be included in the docs, thanks for your suggestion.
