### ISSUE TITLE
Missing structure definition for PlayerData / xPlayer

### ISSUE THREAD

**Issue by lexinor** [esx-framework/esx-documentation#53]
Hi, it would be nice to add documentation for objects such as PlayerData or even xPlayer

**Comment by Benzo00** [comment]
that we can fix :) thanks for the suggestion

**Comment by Benzo00** [comment]
Some small info about the whole playerdata table is now added to docs!

**Comment by lexinor** [comment]
> Some small info about the whole playerdata table is now added to docs!

Good thing ! Thanks
